CREATE TABLE product(
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    price DOUBLE(11,2) NOT NULL,
    amount INT(11) NOT NULL default '0',
    name VARCHAR(200) NOT NULL UNIQUE,
    image VARCHAR(200) NOT NULL,
    descr TEXT(1500) NOT NULL,
    category VARCHAR(30) NOT NULL,
    barcode INT(15) UNIQUE
);